### ISSUE TITLE
Does this class consider ^ and $ as String and not as metacharacter.

### ISSUE THREAD

**Issue by prachi23y** [cs-au-dk/dk.brics.automaton#20]
Automaton automaton1 = RegExp("^GSA").toAutomaton();
        Automaton automaton2 = new RegExp("GSA").toAutomaton();
        System.out.println(automaton2.intersection(automaton1).isEmpty());

it should intersect ,but code gives me that these two patterns are unique.

**Comment by amoeller** [comment]
Please read the documentation, in particular the first item on the FAQ: https://www.brics.dk/automaton/faq.html
