### ISSUE TITLE
Word boundary not working

### ISSUE THREAD

**Issue by vitalyli** [cs-au-dk/dk.brics.automaton#22]
Hi !
Ran into word boundary issue, I have a long list of tokens, some of which I 
need to match with word boundary; Basic Pattern class works, but not Automation.
Any way this can be fixed? 

Automaton p0_AA = new RegExp(".*(something|\\b(blah|foo|goo)\\b)").toAutomaton();
RunAutomaton p0_RA = new RunAutomaton(p0_AA);
System.out.println(p0_RA.run("ba foo nery"));

-->false

Basic regex works with above.

Pattern p0 = Pattern.compile(".*(something|\\b(blah|foo|goo)\\b)");
    String s = "ba foo nery";
    Matcher m = p0.matcher(s);
    if (m.find()) {
      System.out.println("pattern found");
    } else {
      System.out.println("not found");
    }

-->found

**Comment by amoeller** [comment]
Please see the FAQ (https://www.brics.dk/automaton/faq.html).
You can try something like `new RegExp("(.*[\\ ])?[a-z]+([\\ ].*)?")` (modify according to what delimiters and word characters you're interested in).

**Comment by vitalyli** [comment]
Thanks!

 I came up with union of two automata which seem to work.

Below handles starts with ends with, full term and contains type of logic.


Automaton aaC =
new RegExp("(abc | abc | abc|abc)").toAutomaton();

Then the rest I will create 
something like @(blah|foo bar|foxes)@ 

Then union the two.

I’m not sure it makes sense but seem to work.
