### ISSUE TITLE
Error with POM file

### ISSUE THREAD

**Issue by murphd40** [cs-au-dk/dk.brics.automaton#4]
This library is causing dependency check failures in our build pipeline:

> org.xml.sax.SAXParseException: Content is not allowed in prolog.

> An error occurred while analyzing '....gradle\caches\modules-2\files-2.1\dk.brics.automaton\automaton\1.11-8\6ebfa65eb431ff4b715a23be7a750cbc4cc96d0f\automaton-1.11-8.jar' (Central Analyzer).

could you add an xml declaration to your POM file?

https://search.maven.org/#artifactdetails%7Cdk.brics.automaton%7Cautomaton%7C1.11-8%7Cjar

**Comment by amoeller** [comment]
Fixed in d646e15

**Comment by simongregersen** [comment]
The project is now officially available in Maven Central Repository: http://search.maven.org/#artifactdetails%7Cdk.brics%7Cautomaton%7C1.12-1%7Cjar
