### ISSUE TITLE
Some regexes are not properly visualized by `toDot()`

### ISSUE THREAD

**Issue by yuudai-g** [cs-au-dk/dk.brics.automaton#41]
After converting some regular expressions to automata and attempting to visualize them, I found that some regexes are not output correctly. Some examples are shown below.

Output when visualizing `$\{upper:([a-z0-9]|:|\. ||/)`:
![fig1](https://github.com/cs-au-dk/dk.brics.automaton/assets/54973373/38946bb2-ffc2-400f-97ee-0510c15485ad)
In the `([a-z0-9]|:|\. ||/)` part, the output does not contain `0-9`. Also, `:. /`, which is expected to be `. -:` is output.

Output when visualizing `$\{([a-z0-9]|:)+:\-([a-z0-9])+`:
![fig2](https://github.com/cs-au-dk/dk.brics.automaton/assets/54973373/682621a5-f090-4fe3-a1f8-1b155a47330e)
In the `[a-z0-9]` part, the part marked in red is the expected output, while the part marked in blue seems to be redundant.

Some of these regular expressions are improperly visualized, but I get the expected results for matching in both regexes. Are these behaviors due to a bug or the specification of the library?

**Comment by amoeller** [comment]
Please read the documentation https://www.brics.dk/automaton/doc/dk/brics/automaton/RegExp.html and the FAQ https://www.brics.dk/automaton/faq.html.

**Comment by yuudai-g** [comment]
I understand, thanks for your reply.
