### ISSUE TITLE
special chars \d \s \w in regex

### ISSUE THREAD

**Issue by garganti** [cs-au-dk/dk.brics.automaton#6]
It would be very good if brics regex subsystem could support natively special chars \d \s \w. I know that we can substitute those with the corresponding pattern (like [0-9] and so on), but if brics could build the automaton directly, it would be better. Note that these are the most used operators brics is not supporting according to 
Carl Chapman and Kathryn T. Stolee. 2016. Exploring regular expression usage and context in Python. In Proceedings of the 25th International Symposium on Software Testing and Analysis (ISSTA 2016). ACM, New York, NY, USA, 282-293. 
We use brics for generating strings using mutation testing: http://cs.unibg.it/mutrex/ and it works great !

**Comment by amoeller** [comment]
Please see the first and the fifth item on the FAQ: http://www.brics.dk/automaton/faq.html 
The predefined automata listed on http://www.brics.dk/automaton/doc/dk/brics/automaton/Datatypes.html#get(java.lang.String) should cover most needs.

**Comment by RuralHunter** [comment]
Is there any guide or example about how to replace for example '\d' match? The doc in the links above is too hard to understand.

**Comment by amoeller** [comment]
I'm not sure what you mean by "replace for example '\d' match", sorry. The regexp syntax is specified here: https://www.brics.dk/automaton/doc/dk/brics/automaton/RegExp.html

**Comment by RuralHunter** [comment]
I meant how to implement the matching of '\d' with code using automaton, other than replace the '\d' in the regular expression with '[0-9]'.

**Comment by amoeller** [comment]
There is not a one-to-one correspondence between "standard" notation like \d, \w, etc. and the automata provided by default in this package.  You can make a RegExp object like `new RegExp("bla<integer>bla", RegExp.AUTOMATON)`.

**Comment by amoeller** [comment]
Looks like the automaton.jar file (which contains the automata files) is not included in your classpath?

**Comment by RuralHunter** [comment]
do I need additional dependency in pom.xml other than this?
```xml
        <dependency>
            <groupId>dk.brics</groupId>
            <artifactId>automaton</artifactId>
            <version>1.12-4</version>
        </dependency>
```

**Comment by amoeller** [comment]
Use this instead:
```Java
new RegExp("aaa<integer>bbb").toAutomaton(new DatatypesAutomatonProvider())
```

**Comment by RuralHunter** [comment]
yes, it works. Thanks a lot!

**Comment by garganti** [comment]
I still wish that dk.brics supported \d directly ...
